### ISSUE TITLE
Submitting orders returns 400 response. Returns Invalid Request. 

### ISSUE THREAD

**Issue by initishh** [edwarddklee/Python-TradeStation-API-Code#2]
When I am trying to submit the order, I am getting a 400 response with a message saying
`<Message>Invalid Request. The service operation 'Send' expected a value assignable to type 'Order' for input parameter 'order' but received a value of type 'HttpRequestMessage`1'.</Message>`

This is the code.
`url = "https://api.tradestation.com/v2/orders?access_token=" + access_token`
`data = {'AccountKey': {account_key},'AssetType': 'FU', 'Duration': 'DAY', 'OrderType': 'Market', 'Quantity': '1', 'Symbol': {SYMBOL_NAME},'TradeAction': 'BUY'}`
`response = requests.post(url=url, data=data)`
`print(response.text)`
Please help.

**Comment by williammh** [comment]
So what ended up being the issue? I have the same problem

**Comment by initishh** [comment]
Dont remember much. But, the issue was related to the way I was making the api call.
`response = requests.post(url=url, data=data)
`
Can you please check the doc once?

**Comment by williammh** [comment]
Thanks for the quick response. I tried checking the docs. There's not even a mention of a parameter called "orders" for the the confirm order or submit order endpoints. Did the issue have something to do with request headers? There's no mention required headers for these endpoints either

**Comment by williammh** [comment]
For anyone else who finds this page in the future, I fixed the issue by setting 'Content-Type' to 'application/json' in the request headers and also passing in the request body as a json string using json.dumps.


`import json` 

`url = "https://api.tradestation.com/v2/orders?access_token=" + access_token`
`data = {'AccountKey': {account_key},'AssetType': 'FU', 'Duration': 'DAY', 'OrderType': 'Market', 'Quantity': '1', 'Symbol': {SYMBOL_NAME},'TradeAction': 'BUY'}`
`response = requests.post(url=url, data=json.dumps(data), headers={'Content-Type': 'application/json'})`
